image: microsoft/dotnet:latest

stages:
  - build
  - test
  - publish

variables:
  project: "NoData"
  nuget_token: ""

build:
  stage: build
  variables:
    build_path: "$project"
  script:
    - "cd $build_path"
    - "dotnet add package Roslynator.Analyzers"
    - "dotnet build --no-incremental -v q /warnaserror"

test:
  stage: test
  variables:
    test_path: "$project.Tests"
  script:
    - "cd $test_path"
    - "dotnet test"

publish:
  stage: publish
  variables:
    build_path: "$project"
  environment:
    name: production
  script:
    - "cd $build_path"
    - "rm -rf bin"
    - "dotnet pack -v q /warnaserror -c Release"
    - "cd bin/Release"
    - dotnet nuget setapikey $NUGET -Source https://api.nuget.org/v3/index.json
    - dotnet nuget push *.nupkg
